include HC in integration tests

diff --git a/.github/actions/integration-tests/action.yml b/.github/actions/integration-tests/action.yml
--- a/.github/actions/integration-tests/action.yml
+++ b/.github/actions/integration-tests/action.yml
@@ -58,9 +58,41 @@ runs:
       shell: bash
     - run: cd test/incidents-app && npm i
       shell: bash
+
+    - name: Set node env for HANA
+      run: echo "NODE_VERSION_HANA=$(echo ${{ inputs.NODE_VERSION }} | tr . _)" >> $GITHUB_ENV
+      shell: bash
+    # Deploy model to HANA
+    - name: Create HDI Container
+      shell: bash
+      run: cf create-service hana hdi-shared cap-js-print-hana-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-$NODE_VERSION_HANA
+    - run: cd tests/incidents-app/ && cds deploy --to hana:cap-js-print-hana-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-$NODE_VERSION_HANA
+      shell: bash
     # Bind against BTP services
+    - run: cds bind db -2 cap-js-print-hana-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-$NODE_VERSION_HANA -o package.json
     - run: cds bind -2 print-service -o package.json
       shell: bash
     # Run tests in hybrid mode
     - run: cds bind --exec npm run test
       shell: bash
+
+    # Cleanup
+    - name: Delete HDI Container Key
+      if: ${{ always() }}
+      run: cf delete-service-key cap-js-print-hana-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-$NODE_VERSION_HANA cap-js-attachments-hana-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-$NODE_VERSION_HANA-key -f
+      shell: bash
+    # Somehow first delete always fails with a "ongoing operation on service binding" error
+    - name: Delete HDI Container
+      if: ${{ always() }}
+      shell: bash
+      run: |
+        for i in {1..3}; do
+          cf delete-service cap-js-print-hana-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-$NODE_VERSION_HANA -f && break
+          echo "HDI container delete failed, retrying ($i/3)..."
+          sleep 10
+          if [ "$i" -eq 3 ]; then
+            echo "❌ HDI container delete failed after 3 attempts."
+            exit 1
+          fi
+        done
+
